# Generated by Django 5.0.2 on 2024-10-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesa', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_cliente', models.CharField(max_length=50)),
                ('para_llevar', models.BooleanField(default=False)),
                ('tiempo_creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('E', 'En espera'), ('P', 'Preparado'), ('L', 'Listo'), ('S', 'Servido')], default='E', max_length=20)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesa.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='nPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('observaciones', models.TextField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orden.pedido')),
            ],
        ),
    ]
