# Generated by Django 5.0.2 on 2024-10-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('E', 'En espera'), ('P', 'Preparado'), ('L', 'Listo'), ('S', 'Servido')], default='E', max_length=20)),
                ('pedido', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orden.pedido')),
            ],
        ),
    ]
