# Generated by Django 5.0.2 on 2024-10-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=3, max_digits=9)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orden.pedido')),
            ],
        ),
    ]
